FROM eclipse-temurin:21-jre-alpine
RUN addgroup -S app && adduser -S app -G app
COPY service-user/target/service-user-*.jar /app/service-user.jar
RUN chown -R app:app /app
USER app
ENTRYPOINT ["sh", "-c", "java $JAVA_OPTS -jar /app/service-user.jar"]
