FROM eclipse-temurin:21-jre-alpine
RUN addgroup -S app && adduser -S app -G app
COPY service-appointment/target/service-appointment-*.jar /app/service-appointment.jar
RUN chown -R app:app /app
USER app
ENTRYPOINT ["sh", "-c", "java $JAVA_OPTS -jar /app/service-appointment.jar"]
